print("aprendendo isso que ja sei so pra mamanter o foco")
print("para numeros nao precisamos aspas, só colocar o numero dentro dos parenteses")
print(10)
print("agora começa a ficar um poucon interessante, pois como não precisa colocar em aspas facilita pra fazer calculos nos prints")
print(10+5)
print(10+10)
print(10-5)
print(100/2)
print("Podemos colocar várias coisas no mesmo print()")
print("minha idade é, 43")
print("eu tenho", 30, "anos")
print("o resultado de 10 + 5 é", 10+5)

print("Exercícios — 7 minutos")

print("olám mundo")
print("Meu nome é marcelo")
print("Estou aprendendo sixntaxe de python")
print("esta é minha primeira semana")
print("aprendendo programação")
print(25+7)
print (42)
print(25+17)
print("===========================")
print("MEU PRIMEIRO PROGRAMA")
print("===========================")
print("meu nome é marcelo")
print ("estou aprendendo python")
print("10+5 é iigual a",10+5)